fix precommit logic

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -56,5 +56,14 @@ ruff check --select I --fix
 ruff format
 git add -u
 
+if ! ruff check --select I --fix; then
+    echo "linting failed"
+    exit 1
+fi
+
+if ! ruff format; then
+    echo "linting failed"
+    exit 1
+fi
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
