Ben/recategorize tests (#940)
* reduce smoke set; run smoke on automanual flow

* close security issue in CI installer links

* update precommit

* switch headed test for smoke

* default engine dropdown not visible on first page of prefs

* minor fixes

* update key

* update key

* update key

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -60,7 +60,6 @@ fi
 # Lint and format with ruff
 ruff check --select I --fix
 ruff format .
-python addtests.py -q
 git add -u
 
 # if ruff check  doesn't work, we need to fail
@@ -71,6 +70,11 @@ fi
 
 if ! ruff format -q; then
     echo "Formatting failed!"
+    exit 1
+fi
+
+if ! python addtests.py -q; then
+    echo "Manifest missing tests!"
     exit 1
 fi
 # If there are whitespace errors, print the offending file names and fail.
